name: Señale un error
description: ¿Has encontrado un error?Repórtelo aquí
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
     value: |
     Muchas gracias por tu ayuda.Sin embargo, necesitamos una serie de información para ayudarnos.
  - type: checkboxes
    attributes:
      label: "Lista de comprobaciones a realizar antes de validar la apertura del informe de error"
      description: Asegúrese de haber completado el siguiente, si no, su informe puede ser rechazado
      options:
        - label: Logré reproducir el error en el Launcheer Space Client(sin mis modificaciones)
          required: true
        - label: MI Código Respeta La Licencia Creative Commons Zero V1.0 Universal
          required: true
        - label: Mi código cumple con las condiciones de uso del Launcheer Space Client
          required: true
        - label: Me las arreglo para reproducir el error en la última versión del Launcheer Space Client
          required: true
  - type: dropdown
    attributes:
      label: Sistema de explotación
      options:
        - Windows
        - macOS
        - Linux (Base en Debian/Ubuntu)
        - Linux (Otros)
    validations:
      required: true
  - type: input
    attributes:
      label: Versión del sistema operativo
      placeholder: "Ejemplo: Windows 11 Professional 21H2 Build 22000.739 "
    validations:
        required: true
  - type: input
    attributes:
      label: Cometer un hash en el que se cumple el error
      placeholder: 84d7881b67ecf6088205eca6723bfb19bf2a5f0d
  - type: textarea
    attributes:
      label: Comportamiento esperado
      description: Una descripción de lo que debería pasar
      placeholder: El lanzador debería...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportamiento actual
      description: Una descripción de lo que está pasando con el error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Instrucciones para reproducir el objetivo
      placeholder: |
        1. Abra el Launcher
        2. Vaya al menú XYZ
        3. Haga clic en ABC
        4. Observar
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notas adicionales
      placeholder: Detalles adicionales sobre el error, todo lo que podría ser útil
    validations:
      required: false
