blank_issues_enabled: false
contact_links:
  - name: Únase a Discord, para cualquier pregunta o solicitud.
    url: https://discord.gg/ehTebhcu5V
    about: No abrir ningún reporte que no sea para informar errores.
